#Chance to start a horror event every 2000 ticks at night (and in the always dark dimensions) when player has Marked effect
#Default: 20
#Range: 0 ~ 100
marked_event_probability = 20
#Chance to start Sculk Siege event at midnight (and two times per day in the always dark dimensions) when player has Marked effect
#Default: 10
#Range: 0 ~ 100
sculk_siege_event_probability = 10
#Chance to start Apocalyptic Wasteland event when player tries to sleep
#Default: 20
#Range: 1 ~ 100
apocalyptic_wasteland_event_probability = 20
#Chance to burn Charged Totem of Darkness
#Default: 10
#Range: 1 ~ 100
totem_burning_probability = 10
#Replace functional blocks like Crafting Table or Furnace during Apocalyptic Wasteland event
#Default: true
replace_functional_blocks = true
#Maximum spawn height for sculk mobs
#Note: Mobs will be spawned in Deep Dark biome and on top of sculk blocks regardless of this parameter
#Default: -32
#Range: -64 ~ 320
maximum_sculk_mob_spawn_height = -32
#Lifesteal percentage based on damage dealt by Ancient Sword
#Default: 17
#Range: 0 ~ 100
ancient_sword_lifesteal_percentage = 17
#Allowed dimensions with normal daylight cycles for the events
#The events in these dimensions will be triggered only at night
#Warning: Don't include the fixed time dimensions in this list
allowed_normal_dimensions = ["minecraft:overworld"]
#Allowed always dark dimensions for the events
#Usually these dimensions have a fixed time, so the events will be triggered more often
allowed_always_dark_dimensions = ["minecraft:the_nether", "minecraft:the_end", "blue_skies:everdawn", "deeperdarker:otherside", "twilightforest:twilight_forest", "the_bumblezone:the_bumblezone"]

