
[General]
	#If enabled your console will fill with spam showing the various types of data you will need to fine tune this config
	showConsoleIDS = true
	#If selected the rest of the config is pointless. Default: false
	tanningLotion = false
	#Should players burn? Default: false
	burnPlayers = true
	#Should ops NOT burn? Default: true
	noOpBurn = true
	#If enabled armor in the head slot will prevent burning. Default: false
	checkArmor = false
	#If enabled armor will take damage if 'checkArmor' is enabled. Default: false
	damageArmor = false
	#If enabled effects will be checked to see if they prevent burning. Default: false
	checkEffects = true
	#Allow all of a mods' mobs from burning just by specifying the modid. Comma separated and quoted list
	#Default: "iceandfire"
	mods = ["sanitydim"]
	#Allows specific mods' mobs to burn just by specifying their full id for example modid:mobname.  Comma separated and quoted list
	#Default: "minecraft:zombie","minecraft:skeleton"
	mobs = ["minecraft:villager", "sanitydim:rotting_stalker", "sanitydim:sneaking_terror"]
	#Allows specific mods' blocks to be ignored while checking if you are able to see the sky by specifying their full id for example modid:blockname.  Comma separated and quoted list
	#Example: "minecraft:black_stained_glass"
	ignoredBlocks = []
	#If enabled the `dimensions` list will become a blacklist. Default: true
	invertDimensions = true
	#Specify dimensions that allow sun burning by specifying their full id for example modid:dimensionname. (If `invertDimensions` is set to true this turns into a dimension blacklist) 
	#Example: "minecraft:overworld"
	dimensions = []

