
[celesteconfig]

	[celesteconfig.moon]
		#Celestial Configuration
		#Moon Width Scalar
		#Range: 0.0 ~ 100.0
		width = 2.0
		#Moon Height Scalar
		#Range: 0.0 ~ 100.0
		height = 2.0

	[celesteconfig.sun]
		#Sun Width Scalar
		#Range: 0.0 ~ 100.0
		width = 4.0
		#Moon Height Scalar
		#Range: 0.0 ~ 100.0
		height = 4.0

