
#Thank you for downloading Colds Runes.  I had a lot of fun creating it. If you'd like to see some additions, or have any suggestions for this or future mods, join me over on Discord! https://discord.gg/6vpm9Qy
["Rune Settings"]
	"Runes are Perma Locked (Set to false to Change Locked Locations with Crouch + Use)" = true
	"Runes allow you to Teleport across Dimensions" = true
	#Range: 0 ~ 99999999
	"Max Range a Rune can teleport a player (Set to 0 for no Range Limit)" = 0
	#Range: 0 ~ 10000
	"Rune Cooldown in Seconds (Set to 0 for no Cooldown)" = 1
	"Runes are Fire and Lava proof" = true
	#Teleporting Creatures will only work if the Rune is locked to the same Dimension and WILL NOT work on the Ender Dragon or Wither!
	"Runes will Teleport Creatures on hit" = false

["Item Frame Settings"]
	"Stepping onto an ItemFrame with a LOCKED Rune will teleport Players if it's faced UP" = true
	#Invisible Frames will remain invisible even after retrieving the rune.  Break the frame and replace it if you which it to be visible again.
	"Teleporting Frames become invisible when a locked Rune is placed inside of it" = true
	#Item Frame ONLY will cause runes to ONLY teleport if the Rune is inside of an Item Frame.  This Option will disable the Runes (RIGHT CLICK) ability to teleport the player.
	"Item Frame ONLY" = false

["Death Rune Settings"]
	#Death Runes are a one time use Rune that will return you to the place of your death
	"Receive a Death Rune upon dying" = false

["Soulbinding Runes"]
	"Runes are Soulbound and will remain on the player through death" = true
	"If Runes are Soulbound, ONLY hold Locked Runes on death" = false

["Rune Costs"]
	#Range: 0 ~ 100
	"Experience Needed to Teleport with a Rune (Set to 0 for no cost)" = 25
	#Range: 0 ~ 100
	"Experience needed to Lock the Rune(Set to 0 for no cost)" = 0

["Bed Rune Settings"]
	#Range: 0 ~ 100
	"Experience Needed to Teleport with a Bed Rune (Set to 0 for no cost)" = 25
	#Change the Value to adjust how the Bed Rune locks to a location. 1 = Must Wake Up, 2 = Right Clicking a Bed (No Sleep Needed), 3 = Both 1 and 2
	#Range: 1 ~ 3
	Value = 2
	"Bed Runes are Soulbound and will remain on the player through death" = true

