
[grassnotfloating]
	#Support registry entries and tags
	#Please add 'tag:' before tag or the parsing will go wrong
	#'minecraft' namespace is not omittable
	UnfloatableBlocks = ["minecraft:grass", "minecraft:fern", "minecraft:tall_grass", "tag:minecraft:flowers", "tag:minecraft:tall_flowers"]

