#Play sound in cave
play_in_cave = false
#Send messages in other dimensions
send_messages_other_dim = false
#Send messages
send_messages = true
#Play sound in other dimensions
play_in_other_dim = false
#Rooster volume
#Range: 0 ~ 100
rooster_volume = 50
#When should howl Wolf? (time in ticks)
#Range: 10 ~ 23999
evening_tick = 13000
#When should crow Rooster? (time in ticks)
#Range: 10 ~ 23999
morning_tick = 100
#Wolf volume
#Range: 0 ~ 100
wolf_volume = 50

