{
  "configFormat": {
    "version": 2
  },
  "events": {
    "nightZombie": true,
    "nightThunder": true,
    "nightCreeper": true,
    "nightMoon": true,
    "nightGhost": true,
    "nightDark": true,
    "dayLucky": true,
    "dayMiners": true,
    "dayHot": true,
    "dayRain": true,
    "dayFluffing": true,
    "dayBiting": true,
    "dayHungry": true
  },
  "config": {
    "creeperLimit": 384.0,
    "zombieLimit": 384.0,
    "bitingChance": 0.01,
    "fluffMultiplier": 1.0
  }
}